import { FONT_FAMILY } from "@excalidraw/common";

import { randomId } from "@excalidraw/common/random";

import type { UITemplate } from "../index";

const base = {
  roughness: 0,
  fillStyle: "solid" as const,
  opacity: 100,
  isDeleted: false,
  locked: false,
  fontFamily: FONT_FAMILY["system-ui"],
};

export const cardsTemplates: UITemplate[] = [
  {
    id: "card-basic",
    name: "Basic Card",
    category: "cards",
    elements: () => {
      const gid = randomId();
      return [
        {
          id: randomId(),
          type: "rectangle",
          x: 0,
          y: 0,
          width: 280,
          height: 180,
          strokeColor: "#dee2e6",
          backgroundColor: "#ffffff",
          roundness: { type: 3 },
          groupIds: [gid],
          customData: { uiComponent: "card" },
          ...base,
        },
        {
          id: randomId(),
          type: "text",
          x: 16,
          y: 16,
          width: 120,
          height: 20,
          text: "Card Title",
          fontSize: 18,
          textAlign: "left",
          verticalAlign: "top",
          strokeColor: "#212529",
          backgroundColor: "transparent",
          groupIds: [gid],
          customData: { uiComponent: "card-title" },
          ...base,
        },
        {
          id: randomId(),
          type: "line",
          x: 0,
          y: 48,
          width: 280,
          height: 0,
          points: [
            [0, 0],
            [280, 0],
          ],
          strokeColor: "#dee2e6",
          groupIds: [gid],
          customData: { uiComponent: "card-divider" },
          ...base,
        },
        {
          id: randomId(),
          type: "text",
          x: 16,
          y: 60,
          width: 248,
          height: 60,
          text: "Card content goes here.\nAdd details and descriptions.",
          fontSize: 14,
          textAlign: "left",
          verticalAlign: "top",
          strokeColor: "#868e96",
          backgroundColor: "transparent",
          groupIds: [gid],
          customData: { uiComponent: "card-body" },
          ...base,
        },
      ];
    },
  },
  {
    id: "card-image",
    name: "Image Card",
    category: "cards",
    elements: () => {
      const gid = randomId();
      return [
        {
          id: randomId(),
          type: "rectangle",
          x: 0,
          y: 0,
          width: 280,
          height: 300,
          strokeColor: "#dee2e6",
          backgroundColor: "#ffffff",
          roundness: { type: 3 },
          groupIds: [gid],
          customData: { uiComponent: "card" },
          ...base,
        },
        {
          id: randomId(),
          type: "rectangle",
          x: 0,
          y: 0,
          width: 280,
          height: 160,
          strokeColor: "#dee2e6",
          backgroundColor: "#e9ecef",
          groupIds: [gid],
          customData: { uiComponent: "card-image-placeholder" },
          ...base,
        },
        {
          id: randomId(),
          type: "text",
          x: 100,
          y: 70,
          width: 80,
          height: 20,
          text: "Image",
          fontSize: 16,
          textAlign: "center",
          verticalAlign: "middle",
          strokeColor: "#adb5bd",
          backgroundColor: "transparent",
          groupIds: [gid],
          customData: { uiComponent: "card-image-label" },
          ...base,
        },
        {
          id: randomId(),
          type: "text",
          x: 16,
          y: 176,
          width: 120,
          height: 20,
          text: "Card Title",
          fontSize: 18,
          textAlign: "left",
          verticalAlign: "top",
          strokeColor: "#212529",
          backgroundColor: "transparent",
          groupIds: [gid],
          customData: { uiComponent: "card-title" },
          ...base,
        },
        {
          id: randomId(),
          type: "text",
          x: 16,
          y: 206,
          width: 248,
          height: 40,
          text: "Description text here.",
          fontSize: 14,
          textAlign: "left",
          verticalAlign: "top",
          strokeColor: "#868e96",
          backgroundColor: "transparent",
          groupIds: [gid],
          customData: { uiComponent: "card-body" },
          ...base,
        },
      ];
    },
  },
];
